source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/deltaDNA/CocoaPods.git'

platform :ios, '10.0'
#use_frameworks!

target 'DeltaDNADebug_Example' do
    pod 'DeltaDNAAds', '~>1.8.1'
    
    target 'DeltaDNADebug_Tests' do
        inherit! :search_paths
        pod 'Specta', '~>1.0'
        pod 'Expecta', '~>1.0'
    end
end

target 'Notification Content' do
    pod 'DeltaDNADebug', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Enable debug notifications
            if target.name == 'DeltaDNAAds'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DDNA_DEBUG_NOTIFICATIONS=1'
            end
        end
    end
end
