source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/deltaDNA/CocoaPods.git'

platform :ios, '10.0'
#use_frameworks!

target 'DeltaDNADebug_Example' do
    pod 'DeltaDNAAds', '~>1.7.0-beta.2'
    
    target 'DeltaDNADebug_Tests' do
        inherit! :search_paths
        pod 'Specta', '~>1.0'
        pod 'Expecta', '~>1.0'
    end
end

target 'Notification Content' do
    pod 'DeltaDNADebug', :path => '../'
end
